INSERT INTO edb(nombre) values('NIDO');
INSERT INTO edb(nombre) values('HUEVO');
INSERT INTO edb(nombre) values('NEONATO');
INSERT INTO edb(nombre) values('PREINFANTIL');
INSERT INTO edb(nombre) values('INFANTIL');
INSERT INTO edb(nombre) values('PREJUVENIL');
INSERT INTO edb(nombre) values('JUVENIL');
INSERT INTO edb(nombre) values('SUBADULTO');
INSERT INTO edb(nombre) values('ADULTO');
INSERT INTO edb(nombre) values('N/A');

/*INSERT INTO clasificacion(id, nombre_cientifico, nombre_comun) values(1, 'Psittacoidea' , 'Loro');*/
/*INSERT INTO clasificacion(id, nombre_cientifico, nombre_comun) values(2, 'Cacatuidae' , 'Cacatúa');*/
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (1, '﻿Accipiter striatus', 'Gavilán');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (2, 'Agapornis fischeri', 'Perico Fischer');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (3, 'Agapornis personatus', 'Periquito del amor Enmascarado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (4, 'Agapornis roseicollis', 'Inseparable de Namibia');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (5, 'Agapornis sp. ', 'Inseparables');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (6, 'Amazilia tzacatl', 'Amazilia colirrufa');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (7, 'Amazona amazonica', 'Loro Amazonico');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (8, 'Amazona farinosa', 'Lora coronazul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (9, 'Amazona ochrocephala', 'Loro real amazónico');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (10, 'Amazona sp.', 'Loro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (11, 'Ambystoma mexicanum', 'Ajolote');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (12, 'Anas platyrhnchos domesticus', 'Pato doméstico');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (13, 'Anisognathus igniventris', 'Clarinero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (14, 'Anser anser', 'Ganso común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (15, 'Anser cygnoides', 'Ganso Oca Africano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (16, 'Anseriforme domestido no ident.', 'Anseriforme domestido no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (17, 'Anthracothorax nigricollis', 'Mango gorginegro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (18, 'Antrostomus carolinensis', 'Chotacabras de la Carolina');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (19, 'Ara ararauna', 'Guacamaya Azul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (20, 'Ara macao', 'Guacamayo Rojo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (21, 'Ara severus', 'Guacamaya cariseca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (22, 'Ara sp.', 'Guacamaya no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (23, 'Aramides cajanea', 'Chilacoa Colinegra');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (24, 'Archilochus colubris', 'El colibrí de garganta roja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (25, 'Ardea alba', 'Garza blanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (26, 'Asio clamator', 'Búho rayado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (27, 'Asio stygius', 'Búho orejudo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (28, 'Athene cunicularia', 'Mochuelo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (29, 'Aulacorhynchus prasinus', 'Tucan Esmeralda');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (30, 'Aulacorhynchus sp.', 'Tucaneta');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (31, 'Brotogeris jugularis', 'Periquito bronceado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (32, 'Bubulcus ibis', 'Garza Bueyera');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (33, 'Buteo platypterus', 'Aguila aliancha');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (34, 'Buteo swansoni', 'Aguila de swenson');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (35, 'Butorides striata', 'Garza azulada');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (36, 'Butorides virescens', 'Garza verde');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (37, 'Campephilus pollens', 'Carpintero gigante');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (38, 'Caprimulgido no ident.', 'Guarda caminos');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (39, 'Cardellina canadensis', 'Reinita Canadiense');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (40, 'Catharus sp. ', 'Zorzal Migratorio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (41, 'Catharus ustulatus', 'Zorzal buchipecoso');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (42, 'Chaetocercus mulsant', 'Colibrí de Mulsant');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (43, 'Chaetocercus sp.', 'Colibrí');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (44, 'Chloroceryle aenea', 'Martín pescador enano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (45, 'Chlorostilbon sp.', 'Colibri sp.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (46, 'Chordeiles minor', 'Chotacabras migratorio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (47, 'Chordeiles nacunda', 'Caprimulgido desdconocido');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (48, 'Coccyzus americanus', 'Cuclillo americano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (49, 'Coccyzus melacoryphus', 'Cuclillo de Antifaz');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (50, 'Coereba flaveola', 'Mielero común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (51, 'Colaptes rivolii', 'Carpintero Carmesi');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (52, 'Colibri coruscans', 'Colibrí chillón');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (53, 'Colinus cristatus', 'Perdis crestada');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (54, 'Columba livia', 'Paloma doméstica');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (55, 'Columbiforme no ident.', 'Columbiforme no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (56, 'Columbina sp. ', 'Columbina sp. ');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (57, 'Columbina talpacoti', 'Tortolita');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (58, 'Contopus - Empidonax sp.', 'Atrapamoscas');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (59, 'Coragyps atratus', 'Chulo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (60, 'Coturnix coturnix', 'Codorniz');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (61, 'Crotophaga ani', 'Garrapatero común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (62, 'Crotophaga major', 'Garrapatero mayor');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (63, 'Crotophaga sp.', 'Garrapatero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (64, 'Cyanocorax affinis', 'Carriqui pechiblanco');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (65, 'Cyclarhis gujanensis', 'Vireon cejirrufo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (66, 'Dendrocygna autumnalis', 'Pisingo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (67, 'Diglossa cyanea', 'Picaflor de antifaz');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (68, 'Diglossa humeralis', 'Picaflor Negro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (69, 'Diglossa sittoides', 'Picaflor canela');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (70, 'Diglossa sp. ', 'Picaflor');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (71, 'Dumetella carolinensis', 'Pajaro gato gris');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (72, 'Elaenia flavogaster', 'Fiofio copetón');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (73, 'Elanus leucurus', 'Gavilán maromero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (74, 'Eupsittula pertinax', 'Perico carisucio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (75, 'Falco columbarius', 'Esmerejón');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (76, 'Falco sparverius', 'Cernicalo americano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (77, 'Forpus coelestis', 'Perico esmeralda');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (78, 'Forpus conspicillatus', 'Periquito de anteojos');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (79, 'Forpus sp.', 'Periquito sp.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (80, 'Forpus xanthopterygius', 'Cotorrita aliazul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (81, 'Gallinula chloropus', 'Tingua pico rojo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (82, 'Gallinula galeata', 'Gallineta Americana');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (83, 'Gallus gallus domesticus', 'Gallo-Gallina Domestico');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (84, 'Gampsonyx Swainsonii', 'Elanio enano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (85, 'Geotrygon montana', 'Paloma perdiz roja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (86, 'Haplophaedia aureliae', 'Cazoncitos verdoso');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (87, 'Heliornis fulica', 'Pájaro cantil');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (88, 'Herpetotheres cachinnas', 'Halcón risueño');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (89, 'Hirundinidae no ident.', 'Golondrina');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (90, 'Icterus chrysater', 'Turpial montañero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (91, 'Icterus icterus', 'Turpial guajiro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (92, 'Icterus nigrogularis', 'Turpial amarillo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (93, 'Leucophaeus atricilla', 'Gaviota reidora americana');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (94, 'Lonchura atricapilla', 'Capuchino castaño');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (95, 'Lonchura malacca', 'Capuchino tricolor');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (96, 'Lonchura oryzivora', 'Gorrión de Java');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (97, 'Lonchura sp.', 'Capuchino');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (98, 'Lonchura Striata', 'Isabelita de Japon');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (99, 'Mecocerculus leucophrys', 'Tiranuelo Gorgiblanco');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (100, 'Mecocerculus sp.', 'Atrapamoscas menor');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (101, 'Megascops choliba', 'Currucutú');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (102, 'Megascops sp. ', 'Lechuza');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (103, 'Melanerpes formicivorus', 'Carpintero bellotero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (104, 'Meleagris gallopavo domestica', 'Pavo ');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (105, 'Melopsittacus undulatus', 'Periquito australiano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (106, 'Milvago chimachima', 'Caracara chimachima');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (107, 'Mimmus gilvus', 'Sinsonte');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (108, 'Mimus polyglottos', 'Sinsonte norteño');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (109, 'Mniotilta varia', 'Reinita trepadora');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (110, 'Molothrus bonarensis', 'Chamón parasito');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (111, 'Momotus momota', 'Barranquero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (112, 'Myiodynastes luteiventris', 'Atrapamoscas Sulfurado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (113, 'Myiodynastes maculatus', 'Sirirí rayado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (114, 'Neocrex erythrops', 'Polluela piquirroja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (115, 'No identificado', 'No identificado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (116, 'Numida meleagris', 'Gallina de Guinea');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (117, 'Nyctibius griseus', 'Bienparado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (118, 'Nymphicus hollandicus', 'Cacatúa ninfa');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (119, 'Oceanodroma hornbyi', 'Golondrina de la Tempestad de Collar');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (120, 'Ornamentales no ident.', 'Ornamentales varias');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (121, 'Orochelidon murina', 'Golondrina');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (122, 'Ortalis columbiana', 'Guacharaca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (123, 'Ortalis sp.', 'Chachalaca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (124, 'Oxyura andina', 'Pato turrio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (125, 'Paroaria nigrogenis', 'Cardenal enmascarado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (126, 'Paseriforme no ident.', 'Paseriforme no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (127, 'Passer domesticus', 'Gorrión común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (128, 'Passer montanus', 'Gorrión molinero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (129, 'Pavo cristatus', 'Pavo real');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (130, 'Pelecanus occidentalis', 'Pelicano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (131, 'Phimosus infuscatus', 'Ibis negro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (132, 'Picoides fumigatus', 'Carpintero ahumado');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (133, 'Pionites melanocephalus', 'Cotorra Pechiblanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (134, 'Pionus menstruus', 'Cotorra cabeciazul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (135, 'Pionus menstruus sub. Rubrigularis', 'Loro cabeciazul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (136, 'Piranga olivacea', 'Tángara rojinegra migratoria');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (137, 'Piranga rubra', 'Piranga');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (138, 'Pitangus sulphuratus', 'Benteveo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (139, 'Platycercus eximius', 'Perico multicolor');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (140, 'Porphyrio flavirostris', 'Polla llanera');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (141, 'Porphyrio martinica', 'Tingua azul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (142, 'Porzana carolina', 'Polluela norteña');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (143, 'Prothonotary citrea', 'Reinita cabecidorada');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (144, 'Psittaciforme no ident.', 'Psittaciforme no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (145, 'Psittaciformes orna. varios', 'Psittaciformes orna. varios');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (146, 'Psittacula Krameri', 'Cotorra de Kramer');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (147, 'Pygochelidon cyanoleuca', 'Golondrina Azul Blanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (148, 'Quiscalus lugubris', 'Tordo llanero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (149, 'Quiscalus mexicanus', 'Zanate mexicano');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (150, 'Ramphastus sulfuratus', 'Tucan pico iris');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (151, 'Rostrhamus sociabilis', 'Caracolero común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (152, 'Rupicola peruviana', 'Gallito de roca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (153, 'Rupornis magninortris', 'Gavilán pollero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (154, 'Saltator striatipectus', 'Saltator pio judio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (155, 'Serinus canaria', 'Canario doméstico');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (156, 'Setophaga fusca', 'Reinita gorginaranja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (157, 'Sicalis flaveola ', 'Canario costeño');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (158, 'Sorophila sp.', 'Sorophila sp no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (159, 'Spatula discors', 'Barranquete aliazul');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (160, 'Spinus cucullatus', 'Cardenalito de Venezuel');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (161, 'Spinus psaltria', 'Jilguero aliblanco');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (162, 'Spinus sp.', 'Jilguero ');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (163, 'Spinus spinenscens', 'Jilguero andino');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (164, 'Spinus xanthogastrus', 'Jilguero pechinedro');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (165, 'Steatornis caripensis', 'Guacharo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (166, 'Streptelia risoria', 'Torcaza turca albina');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (167, 'Streptopelia roseogrisea', 'Paloma Turca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (168, 'Streptoprocne zonaris', 'Vencejo de collar');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (169, 'Strigiforme no ident.', 'Strigiforme no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (170, 'Sturnella magna', 'Chirlobirlo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (171, 'Sturnus sp.', 'Estonino');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (172, 'Synallaxi subpudica', ' Pijuí de garganta plateada');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (173, 'Systellura longirostris', 'Chotacabras andino');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (174, 'Tachyphonus luctuosus panamensis', 'Tangara caponiblanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (175, 'Taeniopygia guttata', 'Diamante mandarin');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (176, 'Tangara cyanicollis', 'Tangara real');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (177, 'Tangara gyrola', 'Tangara cabecirroja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (178, 'Tangara sp.', 'Tangara sp no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (179, 'Tangara vitriolina', 'Tangara rastrojera');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (180, 'Thalasseus sp.', 'Gaviota migratoria');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (181, 'Thamnophilus multistriatus', 'Batará carcajada');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (182, 'Theristicus caudatus', 'Coclí');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (183, 'Thraupis episcopus', 'Azulejo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (184, 'Thraupis palmarum', 'Azulejo palmero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (185, 'Threnetes leucurus', 'Ermitaño barbudo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (186, 'Tiaris sp. ', 'Tiaris no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (187, 'Trochiliforme no ident.', 'Trochiliforme no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (188, 'Troglodytes aedon', 'Cucarachero común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (189, 'Turdus fuscater', 'Mirla patinaranja');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (190, 'Turdus ignobilis', 'Mirla embarradora');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (191, 'Turdus leucomelas', 'Mirla buchiblanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (192, 'Turdus sp.', 'Mirla no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (193, 'Tyranidae no ident.', 'Tyranidae no ident.');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (194, 'Tyrannus melancholicus', 'Sirirí común');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (195, 'Tyrannus savana', 'Tijereta sabanera');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (196, 'Tyrannus Tyrannus', 'Sirirí migratorio');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (197, 'Tyto alba', 'Lechuza de campanario');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (198, 'Vanellus chilensis', 'Alcaraván llanero');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (199, 'Vireo flavoviridis', 'Vireo verdiamarillo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (200, 'Vireo olivaceus', 'Vireo ojirrojo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (201, 'Vireo sp.', 'Vireo ojirrojo');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (202, 'Zenaida asiatica', 'Torcaza aliblanca');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (203, 'Zenaida auriculata', 'Torcaza');
INSERT INTO clasificacion  (id, nombre_cientifico, nombre_comun) VALUES (204, 'Zonotrichia capensis', 'Copetón');
/*INSERT INTO ave(edb_id,clasificacion_id,nombre) values(1 , 1, 'Roberto')*/

